site_name: Newsoap documentation
site_url: http://newsoap.monomelodies.nl/
repo_url: https://github.com/monomelodies/newsoap

pages:
- Home:
    - 'Quickstart': 'index.md'

copyright: Copyright &copy; 2015, <a href="http://monomelodies.nl/">Marijn Ophorst</a>

